import { Inter } from "next/font/google";
import "./globals.css";
import Header from './components/Header'
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link href="https://fonts.cdnfonts.com/css/helvetica-neue-55" rel="stylesheet"></link>
      <body className={inter.className}>
        <Header />
        {children}</body>
    </html>
  );
}
